import type { StaffInventoryRow } from "@/components/staff/staffInventoryTypes";

function pdfEscape(value: string): string {
  return String(value)
    .replace(/[\\()]/g, (match) => `\\${match}`)
    .replace(/[^\x20-\x7E]/g, " ");
}

function money(value: number): string {
  return (Math.round(value * 100) / 100).toString();
}

function truncate(value: string, max: number): string {
  const text = String(value || "");
  return text.length > max ? `${text.slice(0, max - 1)}...` : text;
}

function unitSummary(rows: StaffInventoryRow[]): string {
  const totals: Record<string, number> = {};
  rows.forEach((row) => {
    totals[row.unit] = (totals[row.unit] || 0) + row.order;
  });
  const parts = Object.keys(totals).map((unit) => `${money(totals[unit])} ${unit}`);
  return parts.join(" / ") || "0";
}

function groupedRows(rows: StaffInventoryRow[]): Record<string, StaffInventoryRow[]> {
  const groups: Record<string, StaffInventoryRow[]> = {};
  rows.forEach((row) => {
    if (!groups[row.category]) groups[row.category] = [];
    groups[row.category].push(row);
  });
  return groups;
}

export function makeStaffInventoryPdfBlob(
  rows: StaffInventoryRow[],
  date: string,
  employee: string,
  venueLabel: string,
): Blob {
  const footerLabel = `Generated by ${venueLabel} Inventory`;
  const titleLabel = `${venueLabel.toUpperCase()} ORDER LIST`;
  const data = rows.filter((row) => row.order > 0);
  const margin = 35;
  const bottom = 38;

  const objs: string[] = [];
  const add = (object: string) => {
    objs.push(object);
    return objs.length;
  };

  const font = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const bold = add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  const text = (x: number, y: number, value: string, size = 10, isBold = false) =>
    `BT /${isBold ? "F2" : "F1"} ${size} Tf ${x} ${y} Td (${pdfEscape(value)}) Tj ET\n`;

  const line = (x1: number, y1: number, x2: number, y2: number, gray = 0.82) =>
    `q ${gray} G 0.5 w ${x1} ${y1} m ${x2} ${y2} l S Q\n`;

  const rect = (x: number, y: number, w: number, h: number, gray = 0.92) =>
    `q ${gray} g ${x} ${y} ${w} ${h} re f Q\n`;

  const pageIds: number[] = [];
  let content = "";
  let y = 0;
  let pageNo = 0;

  const finishPage = () => {
    const contentId = add(
      `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    );
    pageIds.push(
      add(
        `<< /Type /Page /Parent 0 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R /F2 ${bold} 0 R >> >> /Contents ${contentId} 0 R >>`,
      ),
    );
    content = "";
  };

  const tableHeader = () => {
    content += rect(35, y - 4, 525, 18, 0.08);
    content +=
      text(43, y, "#", 8, true) +
      text(62, y, "ITEM", 8, true) +
      text(292, y, "UNIT", 8, true) +
      text(342, y, "CURRENT", 8, true) +
      text(415, y, "NEEDED", 8, true) +
      text(492, y, "ORDER TO BUY", 8, true);
    y -= 22;
  };

  const newPage = () => {
    if (content) {
      content += text(
        35,
        22,
        `${footerLabel} - Page ${pageNo}`,
        8,
        false,
      );
      finishPage();
    }
    pageNo += 1;
    y = 800;
    content = "";
    content += text(35, y, titleLabel, 20, true);
    y -= 24;
    content += text(
      35,
      y,
      `Date: ${date || "-"}    Employee: ${employee || "-"}`,
      11,
      false,
    );
    y -= 18;
    content += text(
      35,
      y,
      `Items to order: ${data.length}    Total order by unit: ${unitSummary(data)}`,
      11,
      true,
    );
    y -= 18;
    content += text(
      35,
      y,
      "Order amount = Needed stock - Current stock. PDF shows only items where order amount is greater than zero.",
      8,
      false,
    );
    y -= 18;
    content += line(35, y, 560, y, 0.65);
    y -= 16;
  };

  const ensure = (height: number) => {
    if (y - height < bottom) {
      content += text(
        35,
        22,
        `${footerLabel} - Page ${pageNo}`,
        8,
        false,
      );
      finishPage();
      newPage();
      tableHeader();
    }
  };

  newPage();

  if (!data.length) {
    content += text(35, y, "No items to order.", 14, true);
  } else {
    const groups = groupedRows(data);
    Object.keys(groups).forEach((category) => {
      ensure(48);
      content += rect(35, y - 3, 525, 19, 0.88);
      content += text(43, y, category.toUpperCase(), 11, true);
      y -= 24;
      tableHeader();
      groups[category].forEach((row, index) => {
        ensure(26);
        const orderText = `${money(row.order)} ${row.unit}`;
        content += text(43, y, String(index + 1), 9, false);
        content += text(62, y, truncate(row.name, 34), 9, true);
        content += text(292, y, row.unit, 9, false);
        content += text(342, y, money(row.current), 9, false);
        content += text(415, y, money(row.needed), 9, false);
        content += text(492, y, orderText, 10, true);
        content += line(35, y - 8, 560, y - 8, 0.88);
        y -= 20;
      });
      y -= 6;
    });
  }

  content += text(
    35,
    22,
    `${footerLabel} - Page ${pageNo}`,
    8,
    false,
  );
  finishPage();

  const pagesId = add(
    `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`,
  );

  const linkedObjs = objs.map((object) =>
    object.replace("/Parent 0 0 R", `/Parent ${pagesId} 0 R`),
  );

  const catalogId = add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);

  let pdf = "%PDF-1.4\n";
  const xref: number[] = [0];

  linkedObjs.forEach((object, index) => {
    xref.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const start = pdf.length;
  pdf += `xref\n0 ${linkedObjs.length + 1}\n0000000000 65535 f \n`;
  xref.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer << /Size ${linkedObjs.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${start}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
}

export function downloadStaffInventoryPdf(
  rows: StaffInventoryRow[],
  date: string,
  employee: string,
  venueLabel: string,
): void {
  const blob = makeStaffInventoryPdfBlob(rows, date, employee, venueLabel);
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${venueLabel.replace(/\s+/g, "")}_Order_${date || "order"}.pdf`;
  anchor.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function shareStaffInventoryPdf(
  rows: StaffInventoryRow[],
  date: string,
  employee: string,
  venueLabel: string,
): Promise<void> {
  const blob = makeStaffInventoryPdfBlob(rows, date, employee, venueLabel);
  const fileName = `${venueLabel.replace(/\s+/g, "")}_Order_${date || "order"}.pdf`;
  const file = new File([blob], fileName, {
    type: "application/pdf",
  });

  try {
    if (navigator.canShare?.({ files: [file] })) {
      await navigator.share({
        files: [file],
        title: `${venueLabel} Order PDF`,
        text: `${venueLabel} order list`,
      });
      return;
    }
  } catch {
    // Fall through to download.
  }

  downloadStaffInventoryPdf(rows, date, employee, venueLabel);
}
